books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.home, name='home'),
    path('books/', views.book_all, name='book_all'),
    path('books/search', views.book_searching, name='book_search'),
    path('books/<slug:slug>/', views.book_detail, name='book_detail'),
    path('category/<slug:slug>/', views.book_filter_by_category, name='book_filter_by_category'),
    path('favourite/', views.favourite_all, name='favourite_all'),
    path('favourite/add/', views.favourite_add, name='favourite_add'),
    path('favourite/delete/', views.favourite_delete, name='favourite_delete'),
    path('history/', views.history_of_user, name='history_of_user'),
]

library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls', namespace='books')),
    path('auth/', include('user_auth.urls', namespace='user_auth')),
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('images/favicon.ico'))),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('books:book_filter_by_category', args=[self.slug])

    def __str__(self):
        return self.name

class Book(models.Model):
    category = models.ForeignKey(Category, related_name='book_category', on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    image_url = models.URLField(blank=True, default='https://hips.hearstapps.com/hmg-prod/images/old-books-arranged-on-shelf-royalty-free-image-1572384534.jpg?crop=0.668xw:1.00xh;0,0&resize=2048:*')
    slug = models.SlugField(max_length=255, unique=True)
    quantity = models.IntegerField(default=1)
    favourite = models.ManyToManyField(
        'auth.User',
        related_name='favourite_books',
        blank=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'books'
        ordering = ('-created_at',)

    def get_absolute_url(self):
        return reverse('books:book_detail', args=[self.slug])

    def __str__(self):
        return self.title

    def is_in_stock(self):
        return self.quantity > 0


class History(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    date_borrowed = models.DateTimeField(auto_now_add=True)
    date_expired = models.DateTimeField()
    date_returned = models.DateTimeField(blank=True, null=True)
    
    class Meta:
        verbose_name_plural = 'histories'
        ordering = ('-date_borrowed',)
        
    def __str__(self):
        return f'{self.book} {self.user}'
    

books/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.db.models import Count
import datetime
from .models import Category, Book, History

# Create your views here.


@login_required(login_url='/auth/login')
def home(request):
    history = History.objects.values('book').annotate(
        book_count=Count('book')).order_by('-book_count')[:3]
    books = Book.objects.filter(id__in=history.values('book'))

    return render(request, 'library/home.html', {'books': books})


@login_required(login_url='/auth/login')
def book_all(request):
    books = Book.objects.all().order_by('title')
    return render(request, 'library/books/index.html', {'books': books})


@login_required(login_url='/auth/login')
def book_detail(request, slug):
    book = get_object_or_404(Book, slug=slug)
    is_favourite = book.favourite.filter(id=request.user.id).exists()
    context = {
        'book': book,
        'is_favourite': is_favourite,
    }
    return render(request, 'library/books/detail.html', context)


@login_required(login_url='/auth/login')
def book_filter_by_category(request, slug):
    category = get_object_or_404(Category, slug=slug)
    books = Book.objects.filter(category=category).order_by('title')
    return render(request, 'library/books/category.html', {'category': category, 'books': books})


@login_required(login_url='/auth/login')
def book_searching(request):
    keyword = request.GET.get('keyword')
    books = Book.objects.filter(title__icontains=keyword)
    context = {
        'keyword': keyword,
        'books': books.order_by('title'),
    }

    return render(request, 'library/books/index.html', context)


@login_required(login_url='/auth/login')
def favourite_all(request):
    books = request.user.favourite_books.all()
    return render(request, 'library/favourite/favourite.html', {'books': books})


@login_required(login_url='/auth/login')
def favourite_add(request):
    if request.POST.get('action') == 'POST':
        book_id = int(request.POST.get('book_id'))
        book = get_object_or_404(Book, id=book_id)
        book.favourite.add(request.user)
        favourite_quantity = request.user.favourite_books.all().count()
        is_favourite = book.favourite.filter(id=request.user.id).exists()
        context = {
            'favourite_quantity': favourite_quantity,
            'is_favourite': is_favourite,
        }
        response = JsonResponse(context)
        return response


@login_required(login_url='/auth/login')
def favourite_delete(request):
    if request.POST.get('action') == 'POST':
        book_id = int(request.POST.get('book_id'))
        book = get_object_or_404(Book, id=book_id)
        book.favourite.remove(request.user)
        favourite_quantity = request.user.favourite_books.all().count()
        is_favourite = book.favourite.filter(id=request.user.id).exists()
        context = {
            'favourite_quantity': favourite_quantity,
            'is_favourite': is_favourite,
        }
        response = JsonResponse(context)
        return response


@login_required(login_url='/auth/login')
def history_of_user(request):
    if request.method == 'POST':
        book_id = request.POST.get('borrowed')
        book = get_object_or_404(Book, id=book_id)

        if book.is_in_stock:
            user = request.user
            history = History(user=user, book=book, date_expired=datetime.datetime.now(
            ) + datetime.timedelta(days=7))
            history.save()
            book.quantity -= 1
            book.save()
            message = "You have successfully borrowed the book."
        else:
            message = "Sorry, this book is not available."

    history = History.objects.filter(user=request.user)
    history_quantity = history.count()
    context = {
        'history': history,
        'history_quantity': history_quantity
    }

    return render(request, 'library/history/index.html', context)

templates/library/books/category.html
{% extends '../base.html' %}
{% load static %}
{% block title %}Category | {{ category.name }}{% endblock title %}

{% block content %}
<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
    <h1 class="display-4 fw-normal">{{ category.name }}</h1>
</div>

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

            {% for book in books %}

            <div class="col">
                <a href="{{ book.get_absolute_url }}" class="text-decoration-none text-dark">
                    <div class="card mb-3" style="max-width: 540px;">
                        <div class="row g-0">
                            <div class="col-md-4">
                                <img src="{{ book.image_url }}" class="img-fluid rounded-start" alt="book-cover">
                            </div>
                            <div class="col-md-8">
                                <div class="card-body">
                                    <h5 class="card-title">{{ book.title|truncatechars:40 }}</h5>
                                    <p class="card-text"><small class="text-muted">{{ book.author }}</small></p>
                                    <p class="card-text">{{ book.description|truncatechars:80 }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>

            {% endfor %}

        </div>
    </div>
</div>
{% endblock %}

templates/library/books/detail.html
{% extends '../base.html' %}
{% load static %}
{% block title %}Book | {{ book.title }}{% endblock title %}

{% block content %}
<div class="me-md-3 pt-3 px-3 pt-md-5 px-md-5 overflow-hidden">
    <img src="{{ book.image_url }}" style="
            position: absolute;
            top: 20%; left: 10%;
            height: 400px;
            border-radius: 5px 21px 21px 5px;
            box-shadow: 1px 1px 2px #26282c,
                        2px 1px 0 #ffffff,
                        4px 2px 0 #ffffff,
                        6px 3px 0 #ffffff,
                        8px 4px 0 #ffffff,
                        10px 5px 0 #ffffff,
                        12px 6px 0 #ffffff,
                        14px 7px 0 #434d54,
                        15px 8px 2px #26282c;
        " />
    <div class="d-flex gap-2" style="position: absolute; top: calc(20% + 440px); left: 10%;">
        <button id="btn-toggle-favourite" value="{{ book.id }}" type="button"
            class="btn {% if is_favourite %}btn-success{% else %}btn-outline-light{% endif %} d-flex align-items-center gap-2">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                class="bi bi-bookmark-star" viewBox="0 0 16 16">
                <path
                    d="M7.84 4.1a.178.178 0 0 1 .32 0l.634 1.285a.178.178 0 0 0 .134.098l1.42.206c.145.021.204.2.098.303L9.42 6.993a.178.178 0 0 0-.051.158l.242 1.414a.178.178 0 0 1-.258.187l-1.27-.668a.178.178 0 0 0-.165 0l-1.27.668a.178.178 0 0 1-.257-.187l.242-1.414a.178.178 0 0 0-.05-.158l-1.03-1.001a.178.178 0 0 1 .098-.303l1.42-.206a.178.178 0 0 0 .134-.098L7.84 4.1z" />
                <path
                    d="M2 2a2 2 0 0 1 2-2h8a2 2 0 0 1 2 2v13.5a.5.5 0 0 1-.777.416L8 13.101l-5.223 2.815A.5.5 0 0 1 2 15.5V2zm2-1a1 1 0 0 0-1 1v12.566l4.723-2.482a.5.5 0 0 1 .554 0L13 14.566V2a1 1 0 0 0-1-1H4z" />
            </svg>
            <span>Favorite</span>
        </button>
        <button type="button" class="btn btn-outline-light d-flex align-items-center gap-2" data-bs-toggle="modal" {% if book.is_in_stock %}data-bs-target="#confirmBorrowModal"{% else %}disabled{% endif %}>
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-inboxes" viewBox="0 0 16 16">
                <path d="M4.98 1a.5.5 0 0 0-.39.188L1.54 5H6a.5.5 0 0 1 .5.5 1.5 1.5 0 0 0 3 0A.5.5 0 0 1 10 5h4.46l-3.05-3.812A.5.5 0 0 0 11.02 1H4.98zm9.954 5H10.45a2.5 2.5 0 0 1-4.9 0H1.066l.32 2.562A.5.5 0 0 0 1.884 9h12.234a.5.5 0 0 0 .496-.438L14.933 6zM3.809.563A1.5 1.5 0 0 1 4.981 0h6.038a1.5 1.5 0 0 1 1.172.563l3.7 4.625a.5.5 0 0 1 .105.374l-.39 3.124A1.5 1.5 0 0 1 14.117 10H1.883A1.5 1.5 0 0 1 .394 8.686l-.39-3.124a.5.5 0 0 1 .106-.374L3.81.563zM.125 11.17A.5.5 0 0 1 .5 11H6a.5.5 0 0 1 .5.5 1.5 1.5 0 0 0 3 0 .5.5 0 0 1 .5-.5h5.5a.5.5 0 0 1 .496.562l-.39 3.124A1.5 1.5 0 0 1 14.117 16H1.883a1.5 1.5 0 0 1-1.489-1.314l-.39-3.124a.5.5 0 0 1 .121-.393zm.941.83.32 2.562a.5.5 0 0 0 .497.438h12.234a.5.5 0 0 0 .496-.438l.32-2.562H10.45a2.5 2.5 0 0 1-4.9 0H1.066z"/>
            </svg>
            <span>{% if book.is_in_stock %}Borrow{% else %}Out of stock{% endif %}</span>
        </button>
    </div>
    <div class="my-3 py-3" style="margin-left: 32%;">
        <h2 class="display-5 d-flex align-items-start justify-content-start gap-4" style="margin-right: 15%;">
            {{ book.title }}
            <button type="button" class="btn btn-outline-dark btn-sm" style="min-width: fit-content;">{{ book.category }}</button>
        </h2>
        <p class="lead">{{ book.author }}</p>
    </div>
    <div class="bg-dark text-light shadow-sm mx-auto d-flex flex-column py-5 align-items-start justify-content-center gap-4"
        style="border-radius: 21px 21px 0 0; padding-left: 32%; padding-right: 15%; min-height: 300px;">
        <div>{{ book.description }}</div>
    </div>

    <form class="form" method="post" action="{% url 'books:history_of_user' %}">  {% csrf_token %}
        <div class="modal fade" id="confirmBorrowModal" tabindex="-1" aria-labelledby="confirmBorrowModalLabel"
            aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="confirmBorrowModalLabel">Confirm borrow</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        Do you want to borrow <strong>"{{book.title}}"</strong>?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-outline-dark" data-bs-dismiss="modal">Close</button>
                        <button id="btn-borrow-book" value="{{ book.id }}" name="borrowed" type="submit"
                            class="btn btn-dark">Borrow</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<script>
    var isFavourite = {{ is_favourite|yesno:"true,false" }};

    function toggleFavorite(url) {
        $.ajax({
            type: 'POST',
            url: url,
            data: {
                'book_id': $('#btn-toggle-favourite').val(),
                'csrfmiddlewaretoken': '{{ csrf_token }}',
                action: 'POST',
            },
            success: function (json) {
                document.getElementById('favourite_quantity').innerHTML = json.favourite_quantity;
                isFavourite = json.is_favourite;
            },
            error: function (xhr, errmsg, err) { },
        })
    }

    $(document).on('click', '#btn-toggle-favourite', function (e) {
        e.preventDefault();
        if (isFavourite) {
            $('#btn-toggle-favourite').removeClass('btn-success');
            $('#btn-toggle-favourite').addClass('btn-outline-light');
            toggleFavorite('{% url "books:favourite_delete" %}')
        } else {
            $('#btn-toggle-favourite').removeClass('btn-outline-light');
            $('#btn-toggle-favourite').addClass('btn-success');
            toggleFavorite('{% url "books:favourite_add" %}')
        }
    })

</script>

{% endblock %}

templates/library/books/index.html
{% extends '../base.html' %}
{% load static %}
{% block title %}Library | Home page{% endblock title %}

{% block content %}
<div class="container d-flex justify-content-center">
    <form role="search" style="width: 60%;" action="{% url 'books:book_search' %}">
        <div class="input-group mb-3">
            <input name="keyword" type="text" class="form-control" placeholder="Searching for a book..."
                aria-label="Searching for a book..." aria-describedby="bth-search-book"
                value="{{ keyword | default:'' }}">
            <button class="btn btn-outline-dark" type="submit" id="bth-search-book">Search</button>
        </div>
    </form>
</div>

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

            {% for book in books %}

            <div class="col">
                <a href="{{ book.get_absolute_url }}" class="text-decoration-none text-dark">
                    <div class="card mb-3" style="max-width: 540px;">
                        <div class="row g-0">
                            <div class="col-md-4">
                                <img src="{{ book.image_url }}" class="img-fluid rounded-start" alt="book-cover">
                            </div>
                            <div class="col-md-8">
                                <div class="card-body">
                                    <h5 class="card-title">{{ book.title|truncatechars:40 }}</h5>
                                    <p class="card-text"><small class="text-muted">{{ book.author }}</small></p>
                                    <p class="card-text">{{ book.description|truncatechars:80 }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
            </div>

            {% endfor %}

        </div>
    </div>
</div>
{% endblock %}